/* empty css                      */(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function d(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=d(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",()=>{const i=document.querySelector(".menu-button"),s=i.querySelector(".icon"),d=document.querySelector(".modal"),a=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const l=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M5.625 7.125H18.375M5.625 16.125H18.375M5.625 11.625H18.375" stroke="#FF51A9" stroke-linecap="round" />
</svg>
    `,o=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M5.25 5.25L12 12M12 12L5.25 18.75M12 12L18.75 18.75M12 12L18.75 5.25" stroke="#FF51A9" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `;i.addEventListener("click",()=>{t=!t,s.innerHTML=t?o:l,t?n():c()}),a.forEach(u=>u.addEventListener("click",()=>{c(),s.innerHTML=l,t=!1})),window.addEventListener("scroll",r);function n(){d.style.display="block"}function c(){d.style.display="none"}function r(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function i(){const o=document.getElementById("site-header");return o?o.offsetHeight:0}function s(o){const n=document.getElementById(o);if(!n)return;const c=i(),r=n.getBoundingClientRect().top+window.pageYOffset-c;window.scrollTo({top:r,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(o=>{o.addEventListener("click",function(n){const c=this.getAttribute("href");if(!c)return;const[r,u]=c.split("#");if(!u)return;const f=window.location.pathname.split("/").pop();!(r===""||r==="./"||r===f||r==="./"+f)||!document.getElementById(u)||(n.preventDefault(),s(u),t(u))})});const a=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(o){e.forEach(c=>c.classList.remove("active"));const n=document.querySelector(`.navigation-item a[href*="#${o}"]`);n&&n.closest(".navigation-item").classList.add("active")}function l(){const o=window.pageYOffset+i()+100;a.forEach(n=>{const c=n.offsetTop,r=c+n.offsetHeight;o>=c&&o<r&&t(n.id)})}if(window.addEventListener("scroll",l),window.location.hash){const o=window.location.hash.substring(1);setTimeout(()=>{s(o),t(o)},300)}});document.addEventListener("DOMContentLoaded",function(){const i=document.getElementById("cookie-popup"),s=document.getElementById("accept-cookies"),d=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(i.style.display="block"),s.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),i.style.display="none"}),d.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),i.style.display="none"})});
//# sourceMappingURL=index.js.map
